# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6270c67c04e4574ca0be827d7546338de5a227a0f9d050d6cbcacd672d9013c00058084ac599c2c77c66d3581ef2407dfb4e78be53f526a6548746739551b305

test:
  secret_key_base: 80ce6cf7061a8f4484d4aa9212a93a23cf2eff40d61e9bac740806b5ccd2912fbb82ad0b583192901a7da97ca33fcb09ae6bd2e1a321b1e11dad74f6828d0cad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
